Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 # File transfers file given to server given as args
+
 # Check if the number of arguments is less than 4
 if [ $# -lt 4 ]; then
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
@@ -12,5 +13,19 @@ server_ip=$2
 username=$3
 ssh_key=$4
 
+# Check if the file to be transferred exists
+if [ ! -f "$file_path" ]; then
+    echo "Error: File '$file_path' does not exist."
+    exit 1
+fi
+
 # Transfer the file using scp with strict host key checking disabled
 scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
+
+# Check if scp command was successful
+if [ $? -eq 0 ]; then
+    echo "File '$file_path' successfully transferred to $username@$server_ip:~/"
+else
+    echo "Error: File transfer failed."
+    exit 1
+fi
